add permissions-policy to all express-served pages
alphagov/paas-admin pull request #1665
Opened 2021-07-14 11:50 UTC by 0atman

-------

What
----
Added a zeroed-out permissions-policy header to all express-served pages (ie, all pages)

Why: To disable FLoC as per https://github.com/alphagov/govuk-rfcs/blob/main/rfc-142-add-interest-cohort-permssion-policy-header.md

How to review
-------------

Run the server locally and observe the new `permissions-policy` header being set.
If on chrome, observe `document.interestCohort()` to be `()`

Who can review
---------------

Any developer
---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

2021-07-14 11:50 UTC, 0atman commented
Tests pass, header set:

![Screenshot from 2021-07-14 12-43-58](https://user-images.githubusercontent.com/114097/125617373-79cb93e6-69be-4207-94a1-a975d212df02.png)

2021-07-14 12:27 UTC, paroxp requested changes
Could we get a test as well?

2021-07-14 12:35 UTC, 0atman commented
Yes! Of course.

2021-07-20 07:15 UTC, kr8n3r approved these changes

2021-07-20 08:10 UTC, merged

2021-07-20 08:10 UTC, 0atman commented
Thanks all :ok_hand: