Move to node v16 and npm v8
alphagov/paas-admin pull request #2218
Opened 2022-01-12 17:43 UTC by kr8n3r

What
----

Node 16 is now active LTS and npm v8 is the current release.

How to review
-------------

- tests pass
- run locally or on dev env to check for any issues

Who can review
---------------

not @kr8n3r 

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

2022-01-12 18:06 UTC, paroxp approved these changes

2022-01-12 18:06 UTC, paroxp requested changes
https://github.com/alphagov/paas-admin/blob/main/.nvmrc :/

2022-01-12 18:11 UTC, kr8n3r commented
> https://github.com/alphagov/paas-admin/blob/main/.nvmrc :/

oops, updated

2022-01-13 08:53 UTC, paroxp approved these changes

2022-01-13 11:03 UTC, merged